framework:
    notifier:
        chatter_transports:
            # WhatsApp via Meta Business API
            whatsapp: '%env(WHATSAPP_DSN)%'
            
            # Slack integration (when needed)
            # slack: '%env(SLACK_DSN)%'
            
        texter_transports:
            # SMS via Twilio (when needed)
            # twilio: '%env(TWILIO_DSN)%'
            
        channel_policy:
            # Map urgency levels to channels for SGV alerts
            urgent: ['chat/whatsapp', 'email', 'browser']  # Critical alerts
            high: ['chat/whatsapp', 'email', 'browser']    # High severity alerts  
            medium: ['email', 'browser']                   # Medium severity alerts
            low: ['browser']                                # Low severity alerts

        admin_recipients:
            - { email: sgv@gesvial.cl }
            - { email: admin@gesvial.cl }
